"""
DataPilot – FastAPI Application
Supports two data source modes:
  1. DB connection (PostgreSQL / Azure SQL) — configured via .env
  2. File upload (Excel / CSV) — uploaded through /api/upload

The knowledge base (markdown file) is generated by Llama on first use
and stored in knowledge_store/. Users can edit the markdown and
changes are reflected immediately on the next query.
"""
from __future__ import annotations
import logging
import re
from contextlib import asynccontextmanager
from datetime import datetime
from pathlib import Path
from typing import Optional, List

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from adapters.base import SQLDialect, SchemaContext
from adapters.postgresql import PostgreSQLAdapter
from adapters.azure_sql import AzureSQLAdapter
from adapters.snowflake import SnowflakeAdapter
from config.settings import get_settings, DBSource
from ingestion.excel_ingester import ingest_file
from knowledge_base.domain_kb import get_domain_list
from knowledge_base.loader import get_all_knowledge_bases
from knowledge_base.markdown_generator import generate_knowledge_base
from knowledge_base.markdown_parser import (
    KBMetadata, KnowledgeStore, init_store, get_store,
)
from llm.model_manager import ModelManager
from llm.ollama import OllamaProvider
from pipeline.nlp_to_sql import (
    NLPToSQLPipeline, get_schema_cached, invalidate_schema_cache,
)

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)

# ── Application state ─────────────────────────────────────────────────────────
_adapters:  dict[str, PostgreSQLAdapter | AzureSQLAdapter] = {}
_pipelines: dict[str, NLPToSQLPipeline] = {}
_schemas:   dict[str, SchemaContext] = {}   # for uploaded files (no DB adapter)
_llm:       Optional[OllamaProvider] = None
_model_mgr: Optional[ModelManager]  = None


def _source_id_for(db_source: DBSource) -> str:
    return f"{db_source.value}"


def _make_pipeline(
    adapter,
    source_id: str,
) -> NLPToSQLPipeline:
    """Create a pipeline, pre-loading concepts and column notes from the KB store."""
    store        = get_store()
    concepts     = store.parse_concepts(source_id)   if store.exists(source_id) else None
    column_notes = store.get_column_notes(source_id) if store.exists(source_id) else {}
    return NLPToSQLPipeline(
        adapter          = adapter,
        llm              = _llm,
        schema_cache_ttl = get_settings().schema_cache_ttl,
        concept_registry = concepts,
        column_notes     = column_notes,
        source_id        = source_id,
    )


# ── Lifespan ──────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _llm, _model_mgr
    s = get_settings()

    # Knowledge store
    store = init_store(s.knowledge_store_path)
    logger.info("Knowledge store: %s", s.knowledge_store_path)

    # Pre-load dialect knowledge bases
    get_all_knowledge_bases()

    # LLM providers
    _llm       = OllamaProvider()
    _model_mgr = ModelManager()
    await _llm.start()
    await _model_mgr.start()
    await _model_mgr.warmup_sql_model()

    # PostgreSQL
    if s.pg_host and s.pg_user and s.pg_database:
        try:
            pg        = PostgreSQLAdapter()
            await pg.connect()
            src_id    = _source_id_for(DBSource.POSTGRESQL)
            _adapters[src_id] = pg
            _pipelines[src_id] = _make_pipeline(pg, src_id)
            logger.info("PostgreSQL ready (source_id=%s)", src_id)
        except Exception as exc:
            logger.warning("PostgreSQL unavailable: %s", exc)

    # Azure SQL
    if s.az_server and s.az_user and s.az_database:
        try:
            az        = AzureSQLAdapter()
            await az.connect()
            src_id    = _source_id_for(DBSource.AZURE_SQL)
            _adapters[src_id] = az
            _pipelines[src_id] = _make_pipeline(az, src_id)
            logger.info("Azure SQL ready (source_id=%s)", src_id)
        except Exception as exc:
            logger.warning("Azure SQL unavailable: %s", exc)

    # Snowflake
    if s.sf_account and s.sf_user and s.sf_database and s.sf_warehouse:
        try:
            sf        = SnowflakeAdapter()
            await sf.connect()
            src_id    = _source_id_for(DBSource.SNOWFLAKE)
            _adapters[src_id] = sf
            _pipelines[src_id] = _make_pipeline(sf, src_id)
            logger.info("Snowflake ready (source_id=%s)", src_id)
        except Exception as exc:
            logger.warning("Snowflake unavailable: %s", exc)

    if not _pipelines:
        logger.warning("No DB connections — upload-only mode active")

    yield

    # Shutdown
    for adapter in _adapters.values():
        await adapter.disconnect()
    await _llm.stop()
    await _model_mgr.stop()


app = FastAPI(
    title       = "DataPilot",
    description = "NLP → SQL with AI-generated business knowledge base",
    version     = "2.0.0",
    lifespan    = lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

FRONTEND_DIR = Path(__file__).parent / "frontend"


# ── Request / Response models ─────────────────────────────────────────────────

class AskRequest(BaseModel):
    question:             str   = Field(..., min_length=1, max_length=2000)
    source_id:            str   = Field(..., description="Which source to query")
    session_id:           str   = Field(default="default")
    conversation_history: List[dict] = []


class GenerateKBRequest(BaseModel):
    source_id: str
    domain:    str


class SaveKBRequest(BaseModel):
    source_id: str
    markdown:  str


class SchemaRefreshRequest(BaseModel):
    db_source: DBSource


# ── Helpers ───────────────────────────────────────────────────────────────────

def _first_source_id() -> Optional[str]:
    if _pipelines:
        return next(iter(_pipelines))
    if _schemas:
        return next(iter(_schemas))
    return None


def _get_pipeline_or_raise(source_id: str) -> NLPToSQLPipeline:
    p = _pipelines.get(source_id)
    if not p:
        raise HTTPException(
            status_code=404,
            detail=f"No active pipeline for source '{source_id}'. "
                   "Available: " + str(list(_pipelines.keys()))
        )
    return p


def _infer_chart_type(columns: list[str], rows: list[dict]) -> str:
    if not rows or not columns:
        return "none"
    if len(rows) == 1 and len(columns) == 1:
        return "number"
    if len(columns) >= 2:
        label_col = columns[0]
        value_col = columns[1]
        if any(kw in label_col.lower() for kw in ("date","month","year","day","time","week")):
            return "line"
        try:
            float(rows[0].get(value_col, ""))
            return "bar" if len(rows) <= 12 else "line"
        except (ValueError, TypeError):
            pass
    return "table"


def _generate_follow_ups(question: str, columns: list[str]) -> list[str]:
    q = question.lower()
    follow_ups = []
    if any(kw in q for kw in ("total","sum","revenue","sales")):
        follow_ups.append("Break this down by month")
    if "top" in q:
        follow_ups.append("Show the bottom performers instead")
    if any(kw in q for kw in ("revenue","sales","amount","profit")):
        follow_ups.append("What is the trend over the last 6 months?")
    if columns:
        follow_ups.append(f"Group by {columns[0]}")
    if not follow_ups:
        follow_ups = ["Show me more details", "Summarize this data"]
    return follow_ups[:3]


def _build_answer(question: str, columns: list, rows: list, error) -> str:
    if error:
        return f"I ran into an error: {error}"
    if not rows:
        return "The query returned no results. The data may not exist for that filter, or try rephrasing."
    if len(rows) == 1 and len(columns) == 1:
        val = rows[0].get(columns[0], "N/A")
        return f"The result is **{val}**."
    return f"Here are the results — **{len(rows)}** row(s) across **{len(columns)}** column(s)."


# ── System endpoints ──────────────────────────────────────────────────────────

@app.get("/health", tags=["System"])
async def health():
    db_status = {}
    for src_id, adapter in _adapters.items():
        db_status[src_id] = await adapter.health_check()
    model_status = await _llm.health_check() if _llm else {}
    return {
        "status":     "ok" if (db_status or _schemas) else "upload-only",
        "databases":  db_status,
        "models":     model_status,
        "uploads":    list(_schemas.keys()),
    }


@app.get("/sources", tags=["System"])
async def list_sources():
    sources = []
    for src_id, adapter in _adapters.items():
        store  = get_store()
        has_kb = store.exists(src_id)
        sources.append({
            "id":       src_id,
            "name":     adapter.source_name,
            "dialect":  adapter.dialect.value,
            "type":     "database",
            "has_kb":   has_kb,
        })
    for src_id, schema in _schemas.items():
        store  = get_store()
        has_kb = store.exists(src_id)
        sources.append({
            "id":      src_id,
            "name":    schema.database,
            "dialect": schema.dialect.value,
            "type":    "upload",
            "has_kb":  has_kb,
        })
    return {"sources": sources}


@app.get("/api/domains", tags=["Knowledge Base"])
async def list_domains():
    return {"domains": get_domain_list()}


# ── File upload ───────────────────────────────────────────────────────────────

@app.post("/api/upload", tags=["Knowledge Base"])
async def upload_file(file: UploadFile = File(...)):
    """
    Upload an Excel (.xlsx/.xls) or CSV file.
    The file is parsed into a SchemaContext and stored in memory.
    Returns the source_id to use for KB generation and queries.
    """
    allowed = {".csv", ".xlsx", ".xls"}
    suffix  = Path(file.filename or "").suffix.lower()
    if suffix not in allowed:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{suffix}'. Allowed: {allowed}",
        )

    content = await file.read()
    try:
        schema, source_id = ingest_file(content, file.filename)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    # Store schema so the KB generator and pipeline can use it
    _schemas[source_id] = schema

    # If we have a KB for this source, create a pipeline for it
    store = get_store()
    if store.exists(source_id) and source_id not in _pipelines:
        _reload_upload_pipeline(source_id, schema)

    return {
        "source_id": source_id,
        "tables":    [t.name for t in schema.tables],
        "has_kb":    store.exists(source_id),
    }


def _reload_upload_pipeline(source_id: str, schema: SchemaContext) -> None:
    """
    Create (or recreate) an in-memory pipeline for an uploaded file.
    Uses a mock adapter backed by the static schema.
    """
    from adapters.base import DatabaseAdapter, QueryResult
    import time as _time

    class StaticAdapter(DatabaseAdapter):
        """Adapter backed by an in-memory SchemaContext (no real DB)."""
        def __init__(self, ctx: SchemaContext) -> None:
            self._ctx = ctx

        @property
        def dialect(self) -> SQLDialect:
            return self._ctx.dialect

        @property
        def source_name(self) -> str:
            return f"upload:{self._ctx.database}"

        async def connect(self) -> None: pass
        async def disconnect(self) -> None: pass
        async def health_check(self) -> bool: return True

        async def fetch_schema(self, schema_name=None) -> SchemaContext:
            return self._ctx

        async def execute(self, sql: str, timeout=None) -> QueryResult:
            return QueryResult(
                sql=sql, columns=[], rows=[], row_count=0,
                execution_ms=0,
                error="Direct execution not supported for uploaded files. "
                      "Connect to a database to run queries.",
            )

        async def explain(self, sql: str) -> str:
            return ""

    store        = get_store()
    concepts     = store.parse_concepts(source_id)   if store.exists(source_id) else []
    column_notes = store.get_column_notes(source_id) if store.exists(source_id) else {}
    adapter  = StaticAdapter(schema)

    _pipelines[source_id] = NLPToSQLPipeline(
        adapter          = adapter,
        llm              = _llm,
        schema_cache_ttl = 0,
        concept_registry = concepts,
        column_notes     = column_notes,
        source_id        = source_id,
    )
    # Pre-populate schema cache
    from pipeline.nlp_to_sql import _schema_cache
    _schema_cache[adapter.source_name] = (schema, _time.time())
    logger.info("Upload pipeline ready: %s", source_id)


# ── Knowledge Base generation ─────────────────────────────────────────────────

@app.post("/api/generate-kb", tags=["Knowledge Base"])
async def generate_kb(req: GenerateKBRequest):
    """
    Generate (or regenerate) the markdown knowledge base for a source.
    Uses Llama to analyse the schema and write a business knowledge document.
    The model unloads from VRAM when done (sequential loading pattern).
    """
    source_id = req.source_id
    domain    = req.domain

    # Resolve schema — from DB adapter or uploaded file
    schema: Optional[SchemaContext] = None

    if source_id in _adapters:
        adapter = _adapters[source_id]
        try:
            schema = await get_schema_cached(adapter)
        except Exception as exc:
            raise HTTPException(status_code=503, detail=f"Schema fetch failed: {exc}")

    elif source_id in _schemas:
        schema = _schemas[source_id]

    else:
        raise HTTPException(
            status_code=404,
            detail=f"Source '{source_id}' not found. Upload a file or check DB connection.",
        )

    # Generate markdown
    try:
        markdown = await generate_knowledge_base(
            schema        = schema,
            domain        = domain,
            source_id     = source_id,
            model_manager = _model_mgr,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))

    # Save to knowledge store
    store = get_store()
    meta  = KBMetadata(
        source_id    = source_id,
        domain       = domain,
        generated_at = datetime.now().isoformat(timespec="seconds"),
        table_count  = len(schema.tables),
    )
    store.save(source_id, markdown, meta)

    # Hot-reload concepts and column notes into any existing pipeline
    concepts     = store.parse_concepts(source_id)
    column_notes = store.get_column_notes(source_id)
    if source_id in _pipelines:
        _pipelines[source_id].refresh_concepts(concepts)
        _pipelines[source_id].refresh_column_notes(column_notes)
    elif source_id in _schemas:
        _reload_upload_pipeline(source_id, _schemas[source_id])

    return {
        "source_id":     source_id,
        "domain":        domain,
        "concepts_found": len(concepts),
        "markdown_size": len(markdown),
        "generated_at":  meta.generated_at,
    }


# ── Knowledge Base CRUD ───────────────────────────────────────────────────────

@app.get("/api/kb/{source_id}", tags=["Knowledge Base"])
async def get_kb(source_id: str):
    """Return the current markdown knowledge base for a source."""
    store = get_store()
    md    = store.load_markdown(source_id)
    if md is None:
        raise HTTPException(status_code=404, detail=f"No KB found for '{source_id}'")
    meta = store.load_metadata(source_id)
    return {
        "source_id": source_id,
        "markdown":  md,
        "metadata":  meta.__dict__ if meta else None,
    }


@app.put("/api/kb/{source_id}", tags=["Knowledge Base"])
async def save_kb(source_id: str, req: SaveKBRequest):
    """
    Save user-edited markdown back to the knowledge store.
    Re-parses concepts so changes take effect immediately.
    """
    store = get_store()
    try:
        store.update_markdown(source_id, req.markdown)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc))

    # Hot-reload into pipeline
    concepts     = store.parse_concepts(source_id)
    column_notes = store.get_column_notes(source_id)
    if source_id in _pipelines:
        _pipelines[source_id].refresh_concepts(concepts)
        _pipelines[source_id].refresh_column_notes(column_notes)

    return {
        "saved":          True,
        "concepts_found": len(concepts),
        "source_id":      source_id,
    }


@app.delete("/api/kb/{source_id}", tags=["Knowledge Base"])
async def delete_kb(source_id: str):
    """Delete the KB for a source (forces re-generation on next use)."""
    store = get_store()
    if not store.exists(source_id):
        raise HTTPException(status_code=404, detail=f"No KB for '{source_id}'")
    store.delete(source_id)
    # Reset pipeline to no concepts
    if source_id in _pipelines:
        _pipelines[source_id].refresh_concepts([])
    return {"deleted": True, "source_id": source_id}


@app.get("/api/kb/{source_id}/status", tags=["Knowledge Base"])
async def kb_status(source_id: str):
    """Check if a KB exists for a source and return its metadata."""
    store = get_store()
    exists = store.exists(source_id)
    meta   = store.load_metadata(source_id) if exists else None
    return {
        "source_id": source_id,
        "exists":    exists,
        "metadata":  meta.__dict__ if meta else None,
    }


# ── Schema refresh ────────────────────────────────────────────────────────────

class SchemaRefreshRequest(BaseModel):
    db_source: DBSource


@app.post("/schema/refresh", tags=["System"])
async def refresh_schema(req: SchemaRefreshRequest):
    src_id  = _source_id_for(req.db_source)
    adapter = _adapters.get(src_id)
    if not adapter:
        raise HTTPException(status_code=404, detail=f"Source '{src_id}' not connected")
    invalidate_schema_cache(adapter)
    schema = await get_schema_cached(adapter, ttl=0)
    return {
        "refreshed": True,
        "source_id": src_id,
        "tables":    len(schema.tables),
        "database":  schema.database,
    }


# ── Query endpoint ────────────────────────────────────────────────────────────

@app.post("/api/ask", tags=["Query"])
async def api_ask(req: AskRequest):
    """
    Main chat endpoint. Converts a natural language question to SQL
    using the knowledge base for the given source.
    """
    source_id = req.source_id or _first_source_id()
    if not source_id:
        raise HTTPException(
            status_code=503,
            detail="No data source available. Upload a file or configure a database.",
        )

    pipeline = _get_pipeline_or_raise(source_id)
    scoped_session = f"{source_id}:{req.session_id}"

    result   = await pipeline.run(req.question, session_id=scoped_session)
    api_resp = result.to_api_response()

    columns = api_resp["data"]["columns"]
    rows    = api_resp["data"]["rows"]
    error   = api_resp.get("error")

    return {
        "answer":           _build_answer(req.question, columns, rows, error),
        "sql":              api_resp["sql"],
        "data":             api_resp["data"],
        "chart_type":       _infer_chart_type(columns, rows),
        "source_id":        source_id,
        "execution_time_ms": api_resp["timing"]["total_ms"],
        "row_count":        api_resp["data"]["row_count"],
        "follow_ups":       _generate_follow_ups(req.question, columns),
        "validation":       api_resp["validation"],
        "error":            error,
    }


# ── Frontend health ───────────────────────────────────────────────────────────

@app.get("/api/health", tags=["System"])
async def api_health():
    src_id = _first_source_id()
    store  = get_store()
    has_kb = store.exists(src_id) if src_id else False
    return {
        "status":    "healthy" if src_id else "no_source",
        "source_id": src_id,
        "has_kb":    has_kb,
        "sources":   list(_pipelines.keys()),
    }


# ── Frontend ──────────────────────────────────────────────────────────────────

@app.get("/", response_class=FileResponse, tags=["Frontend"])
async def serve_frontend():
    index = FRONTEND_DIR / "index.html"
    if not index.exists():
        raise HTTPException(status_code=404, detail="Frontend not found")
    return FileResponse(str(index), media_type="text/html")


if __name__ == "__main__":
    import uvicorn
    s = get_settings()
    uvicorn.run("main:app", host=s.host, port=s.port, reload=s.debug)
